"""
Django settings for ssv_aari_work project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cgi_&l)@b9+1$_9!qv%2yvdhpv#1l#-=)o97@dsp+z-h*^@o32'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'ssv_aari_work.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ssv_aari_work.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration
DEFAULT_FROM_EMAIL = 'mugu.7533@gmail.com'
ADMIN_EMAIL = 'mugu.7533@gmail.com'  # Your Gmail address

# SMTP Email backend settings for Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mugu.7533@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'joiz tucr prse jfkd'  # Generate app password from Gmail

# For development (prints to console instead of sending)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Jazzmin Admin Configuration
# JAZZMIN_SETTINGS = {
#     # Title of the window (will be displayed in the browser tab)
#     "site_title": "SSV ARRI WORK Admin",
#
#     # Title on the login screen (19 chars max)
#     "site_header": "SSV ARRI WORK",
#
#     # Title on the brand (19 chars max)
#     "site_brand": "SSV ARRI WORK",
#
#     # Logo to use for your site, must be present in static files, used for brand on top left
#     "site_logo": None,
#
#     # Logo to use for your site, must be present in static files, used for login form logo
#     "login_logo": None,
#
#     # Logo to use for login form in dark themes
#     "login_logo_dark": None,
#
#     # CSS classes that are applied to the logo above
#     "site_logo_classes": "img-circle",
#
#     # Relative path to a favicon for your site, will default to site_logo if absent
#     "site_icon": None,
#
#     # Welcome text on the login screen
#     "welcome_sign": "Welcome to SSV ARRI WORK Admin",
#
#     # Copyright on the footer
#     "copyright": "SSV ARRI WORK © 2025",
#
#     # List of model admins to search from the search bar, search bar omitted if excluded
#     "search_model": ["auth.User", "auth.Group"],
#
#     # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
#     "user_avatar": None,
#
#     ############
#     # Top Menu #
#     ############
#
#     # Links to put along the top menu
#     "topmenu_links": [
#         # Url that gets reversed (Permissions can be added)
#         {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         {"model": "auth.User"},
#     ],
#
#     #############
#     # User Menu #
#     #############
#
#     # Additional links to include in the user menu on the top right
#     "usermenu_links": [
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         {"model": "auth.user"}
#     ],
#
#     #############
#     # Side Menu #
#     #############
#
#     # Whether to display the side menu
#     "show_sidebar": True,
#
#     # Whether to aut expand the menu
#     "navigation_expanded": True,
#
#     # Hide these apps when generating side menu e.g (auth)
#     "hide_apps": [],
#
#     # Hide these models when generating side menu (e.g auth.user)
#     "hide_models": [],
#
#     # List of apps (and/or models) to base side menu ordering off of
#     "order_with_respect_to": ["auth", "main"],
#
#     # Custom links to append to app groups, keyed on app name
#     "custom_links": {
#         "main": [{
#             "name": "Make Messages",
#             "url": "make_messages",
#             "icon": "fas fa-comments",
#             "permissions": ["main.view_main"]
#         }]
#     },
#
#     # Custom icons for side menu apps/models
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "main": "fas fa-crown",
#         "main.HeroSection": "fas fa-home",
#         "main.Service": "fas fa-concierge-bell",
#         "main.Collection": "fas fa-boxes",
#         "main.Arrival": "fas fa-truck",
#         "main.AcademySection": "fas fa-graduation-cap",
#         "main.GalleryItem": "fas fa-images",
#         "main.Feature": "fas fa-star",
#         "main.AboutHeroSection": "fas fa-info-circle",
#         "main.AboutStory": "fas fa-book",
#         "main.AboutMissionVision": "fas fa-bullseye",
#         "main.AboutValue": "fas fa-gem",
#         "main.AboutReason": "fas fa-check-circle",
#         "main.AboutCTA": "fas fa-rocket",
#         "main.AcademyHero": "fas fa-graduation-cap",
#         "main.AcademyIntroduction": "fas fa-book-open",
#         "main.AcademyCourse": "fas fa-chalkboard-teacher",
#         "main.AcademyBenefit": "fas fa-gift",
#         "main.AcademyTestimonial": "fas fa-comments",
#         "main.AcademyCTA": "fas fa-rocket",
#     },
#
#     # Icons that are used when one is not manually specified
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
#
#     #################
#     # Related Modal #
#     #################
#
#     # Use modals instead of popups
#     "related_modal_active": False,
#
#     #############
#     # UI Tweaks #
#     #############
#
#     # Relative paths to custom CSS/JS scripts (must be present in static files)
#     "custom_css": "css/admin_enhanced.css",
#     "custom_js": None,
#
#     # Whether to show the UI customizer on the sidebar
#     "show_ui_builder": True,
#
#     ###############
#     # Change view #
#     ###############
#
#     # Render out the change view as a single form, or in tabs, current options are
#     # - single
#     # - horizontal_tabs (default)
#     # - vertical_tabs
#     # - collapsible
#     # - carousel
#     "changeform_format": "horizontal_tabs",
#
#     # Override the default submit button text
#     "changeform_format_overrides": {"main": "collapsible"},
#
#     # Add a language dropdown into the admin
#     "language_chooser": False,
# }

# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": False,
#     "accent": "accent",
#     "navbar": "navbar-white navbar-light",
#     "no_navbar_border": False,
#     "navbar_fixed": False,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": False,
#     "sidebar": "sidebar-dark-primary",
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": False,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": False,
#     "theme": "default",
#     "dark_mode_theme": None,
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     },
#     "actions_sticky": "top",
# }
